sudo: required
services:
    - docker 
 
before_install:
    - docker build -t dockerwissem/wissem -f ./client/Dockerfile.dev ./client
script:
    - docker run dockerwissem/wissem npm test -- --coverage
after_success:
    - docker build -t dockerwissem/wissem1 ./client
    - docker build -t dockerwissem/wissem2 ./nginx
    - docker build -t dockerwissem/wissem3 ./server
    - docker build -t dockerwissem/wissem4 ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push dockerwissem/wissem1
    - docker push dockerwissem/wissem2
    - docker push dockerwissem/wissem3
    - docker push dockerwissem/wissem3